name:                mindsl-parser
version:             0.1.0.0
github:              "shiro-el/MinDSL"
license:             MIT
author:              "Jaewhan Lee"
maintainer:          "jae0406whan@gmail.com"
copyright:           "2025 Jaewhan Lee"

extra-source-files:
- README.md
- CHANGELOG.md

synopsis:            Parser for MinDSL (Minimal DSL for psychological assessments)
category:            Language
description:         Please see the README on GitHub at <https://github.com/jae/mindsl#readme>

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src
  exposed-modules:
    - MinDSL.AST
    - MinDSL.Lexer
    - MinDSL.Parser
    - MinDSL.JSON
    - MinDSL.Options
    - MinDSL.TypeScript
  dependencies:
    - base >= 4.7 && < 5
    - text
    - megaparsec >= 9.0
    - parser-combinators
    - aeson
    - aeson-pretty
    - aeson-typescript
    - bytestring
    - containers
    - mtl
    - vector

executables:
  mindsl-parser:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - base >= 4.7 && < 5
    - text
    - megaparsec >= 9.0
    - parser-combinators
    - aeson
    - aeson-pretty
    - bytestring
    - containers
    - mtl
    - vector
    - mindsl-parser
    - optparse-applicative

tests:
  mindsl-parser-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - base >= 4.7 && < 5
    - text
    - megaparsec >= 9.0
    - parser-combinators
    - aeson
    - aeson-pretty
    - bytestring
    - containers
    - mtl
    - vector
    - mindsl-parser
    - hspec
    - hspec-megaparsec
